package mybatis.dao;

import mybatis.model.Moderator;
import org.mybatis.cdi.Mapper;

import java.util.List;


@Mapper
public interface ModeratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODERATOR
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODERATOR
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int insert(Moderator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODERATOR
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    Moderator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODERATOR
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    List<Moderator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MODERATOR
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    int updateByPrimaryKey(Moderator record);
}
