package mybatis.model;

import java.util.List;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private String title;

    private List<Event> events;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.ID
     *
     * @return the value of PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.ID
     *
     * @param id the value for PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLIENT.TITLE
     *
     * @return the value of PUBLIC.CLIENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLIENT.TITLE
     *
     * @param title the value for PUBLIC.CLIENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    public List<Event> getEvents() {return this.events;}
}