package mybatis.model;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EVENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EVENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EVENT.ID
     *
     * @return the value of PUBLIC.EVENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EVENT.ID
     *
     * @param id the value for PUBLIC.EVENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EVENT.TITLE
     *
     * @return the value of PUBLIC.EVENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EVENT.TITLE
     *
     * @param title the value for PUBLIC.EVENT.TITLE
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }
}