package mybatis.model;

import java.util.List;

public class Moderator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLIENT.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODERATOR.FULLNAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private String fullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODERATOR.ID
     *
     * @return the value of PUBLIC.MODERATOR.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODERATOR.ID
     *
     * @param id the value for PUBLIC.MODERATOR.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODERATOR.FULLNAME
     *
     * @return the value of PUBLIC.MODERATOR.FULLNAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODERATOR.FULLNAME
     *
     * @param fullname the value for PUBLIC.MODERATOR.FULLNAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
}