package mybatis.model;

public class Moderator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODERATOR.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODERATOR.NAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODERATOR.EVENT_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer eventId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODERATOR.ID
     *
     * @return the value of PUBLIC.MODERATOR.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODERATOR.ID
     *
     * @param id the value for PUBLIC.MODERATOR.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODERATOR.FULLNAME
     *
     * @return the value of PUBLIC.MODERATOR.FULLNAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODERATOR.FULLNAME
     *
     * @param name the value for PUBLIC.MODERATOR.FULLNAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setFullname(String name) {
        this.fullname = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODERATOR.EVENT_ID
     *
     * @return the value of PUBLIC.MODERATOR.EVENT_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODERATOR.EVENT_ID
     *
     * @param eventId the value for PUBLIC.MODERATOR.EVENT_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
}